### PR TITLE
Added 123jaloezie base

### PR DESCRIPTION
**Pull request by Erwin537**
Modified version of the base that fits blinds from 123jaloezie.nl (and probably some others that use the same factory).

Changes from the base:
- less tall
- motor is offset from the center as the tilt axis is off-center in the base
- wider base

An small disadvantage: because of the decreased height the blue stepper motor cover doesn't fit anymore. I left it of and put some isolation tape on the contacts to prevent it making contact with the metal.

### CODE REVIEW

**Comment by pieterdevriesch** [comment]
Do you happen to have any photos of how you installed it? I have a blind from 123 but I'm afraid it might not have enough space due to being a fairly short one.

**Comment by Erwin537** [comment]
Hi Pieter, unfortunately I don't have any pictures, I removed them from the housing all together because I am moving to another place soon. I did take out the manual way of tilting the blinds however. The wheel is sort of a friction fit, so you can just kind of tilt/slide it out. The rod can also be moved a bit, so that's what I did. I think mine are about 96cm wide. 

If needed you should be able to easily make the servo housing smaller. Just use an online editor and remove part of it. I don't think it really serves a purpose.

**Comment by pieterdevriesch** [comment]
Thanks for the info, that already helps, I missed the part about removing the manual adjustment at first. Without that one it should fit no problem. I'll just hang a Tradfri button for manual adjustment. Actually the empty part of the stepper housing was quite handy since it just manages to hold all of my electronics (D1, power and stepperboard), so that I only have 2 DC wires coming out and being slightly visible (planning to add some white heatshrink to hide them better)

**Comment by Erwin537** [comment]
Excellent 👍 That's a nice and clean install indeed. I am curious, I found that my blinds seemed to be on the heavy side for the servo which couldn't always close/open them. Is that working properly for you? And what size blinds do you (roughly) have?

Btw, for manual tilting I just kind of grab the ribbon or one of the blinds and move it manually. I noticed I was doing that more and more anyway. Removing the wire for tilting cleaned it up a bit as well, so you don't have all those wires hanging around.

**Comment by pieterdevriesch** [comment]
I only just installed it but it worked perfectly. 
DB3DFA19-A27D-4CA9-A13F-A81266FFB498
I'll make a small hole for the wire later when I've found some white heatshrink. The width is also just under 1m but I've got bamboo slats, maybe that makes it lighter. I do have to adjust the travel because the default of 12 steps is about 8 too many. When it hits the end it just clicks.

**Comment by pieterdevriesch** [comment]
[The blinds in motion.](https://youtu.be/uMqEKJmIxM) Do yours also have the non smooth motion? You can really tell the steps the motor is making. It was already like that when the motor was on my desk during testing.

**Comment by Erwin537** [comment]
Looking good!

Unfortunately it says the video is no longer available. But I did see the obvious steps, bit shocky motion. Didn't bother me as much, but (I think) because of the weight it was really unreliable. It would open, but "miss" a lot of steps. Closing was too tough and would miss a lot even more steps resulting in just slightly tilted blinds. 

Maybe in my next house I will opt for the bamboo ones as well. I think the windows might be slightly smaller too.

**Comment by pieterdevriesch** [comment]
[Weird, how about this one?](https://youtu.be/uMqEKJmIxM8) 
https://youtu.be/uMqEKJmIxM8

Hope this one works.

**Pull request merged**
